# Author: Rainer Krug, Rainer@krugs.de

language: minimal
os: osx
osx_image: xcode10.1

before_install:
  - brew update
  - brew tap grass-gis/grass-dev
  - brew tap osgeo/osgeo4mac
  - brew update
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f /usr/local/include/c++ ; fi
  - brew install gcc
  - sw_vers

before_script:
  - export CXX="g++-6" CC="gcc-6"

script:
  - travis_wait 30 brew install --HEAD
    --with-ffmpeg
    --with-liblas
    --with-mysql
    --with-netcdf
    --with-openblas
    --with-postgresql
    grass-trunk
    --only-dependencies
  - travis_wait 30 brew install --HEAD
    --with-ffmpeg
    --with-mysql
    --with-netcdf
    --with-openblas
    --with-postgresql
    grass-trunk
  - travis_wait 30 brew test -v grass-trunk
  - brew info grass-trunk
  - brew uninstall grass-trunk

notifications:
        email:
            recipients:
                - Rainer@krugs.de
            on_success: change
            on_failure: always
